### ISSUE TITLE
[Release Checklist] 1.10.0 RC2

### ISSUE THREAD

**Issue by kmova** [openebs/e2e-tests#339]
- [x] OpenShift Pipeline 
- [x] Konvoy Pipeline 
- [x] Native K8s Pipeline 
- [x] Upgrade Pipelines
     - [x]  1.0 to 1.10.0 RC2 
     - [x]  1.1 to 1.10.0 RC2 
     - [x]  1.2 to 1.10.0 RC2 
     - [x]  1.3 to 1.10.0 RC2
     - [x]  1.4 to 1.10.0 RC2 
     - [x]  1.5 to 1.10.0 RC2 
     - [x]  1.6 to 1.10.0 RC2 
     - [x]  1.7 to 1.10.0 RC2 
     - [x]  1.8 to 1.10.0 RC2 
     - [x]  1.9 to 1.10.0 RC2 
- [x] ZFS Upgrade Pipelines
     - [x]  0.4 to 0.7.0 RC2
     - [x]  0.4.1 to 0.7.0 RC2
     - [x]  0.5 to 0.7.0 RC2
     - [x]  0.6 to 0.7.0 RC2 
     - [x]  0.6.1 to 0.7.0 RC2 
- Manual Tests
   - [x] Test with Helm Chart
   - [ ] <if any fixes came in to RC2>
- Dogfooding
   - [x] Director Online Staging 1.9.0 RC2 to 1.10.0 RC2
 
Additional One-off tasks:
  - [ ] GitLab E2e Infra - disks need to be upgraded.
