### ISSUE TITLE
[Release Checklist] 1.12.0 RC1

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/e2e-tests#395]
- [x] OpenShift Pipeline 
- [x] Konvoy Pipeline 
- [x] Native K8s Pipeline 
- Upgrade Pipelines
     - [x]  1.0 to 1.12.0 RC1 
     - [x]  1.1 to 1.12.0 RC1 
     - [x]  1.2 to 1.12.0 RC1 
     - [x]  1.3 to 1.12.0 RC1 
     - [x]  1.4 to 1.12.0 RC1 
     - [x]  1.5 to 1.12.0 RC1 
     - [x]  1.6 to 1.12.0 RC1 
     - [x]  1.7 to 1.12.0 RC1 
     - [x]  1.8 to 1.12.0 RC1 
     - [x]  1.9 to 1.12.0 RC1
     - [x] 1.10.0 to 1.12.0-RC1
     - [x] 1.11.0 to 1.12.0-RC1
- ZFS Upgrade Pipelines
     - [x]  v0.4 to 0.9.0 RC1 
     - [x]  0.4.1 to 0.9.0 RC1 
     - [x]  0.5 to 0.9.0 RC1 
     - [x]  0.6.0 to 0.9.0 RC1 
     - [x]  0.6.1 to 0.9.0 RC1
     - [x] 0.7.0 to 0.9.0 RC1
     - [x] 0.8.0 to 0.9.0 RC1

- manual tests
    - [x] cspc validation
    - [x] rename spc while migration
    - [x] replica status in cspi
    - [x] zfs pv shared mount

**Comment by kmova** [comment]
@nsathyaseelan @gprasath @w3aman @shashank855  - here are the RC1 images. 

Note the changes in the NDM image path. 

```
openebs/linux-utils:1.12.0-RC1

openebs/node-disk-exporter:0.7.0-RC1
openebs/node-disk-operator:0.7.0-RC1
openebs/node-disk-manager:0.7.0-RC1

openebs/cstor-istgt:1.12.0-RC1
openebs/cstor-pool:1.12.0-RC1

openebs/jiva:1.12.0-RC1

openebs/snapshot-provisioner:1.12.0-RC1
openebs/snapshot-controller:1.12.0-RC1
openebs/openebs-k8s-provisioner:1.12.0-RC1
openebs/admission-server:1.12.0-RC1
openebs/m-upgrade:1.12.0-RC1
openebs/m-exporter:1.12.0-RC1
openebs/cstor-volume-mgmt:1.12.0-RC1
openebs/cstor-pool-mgmt:1.12.0-RC1
openebs/m-apiserver:1.12.0-RC1
openebs/velero-plugin:1.12.0-RC1

openebs/zfs-driver:0.9.0-RC1

openebs/provisioner-localpv:1.12.0-RC1

openebs/migrate-amd64:1.12.0-RC1
openebs/upgrade-amd64:1.12.0-RC1
openebs/cstor-webhook-amd64:1.12.0-RC1
openebs/cstor-pool-manager-amd64:1.12.0-RC1
openebs/cstor-volume-manager-amd64:1.12.0-RC1
openebs/cspc-operator-amd64:1.12.0-RC1
openebs/cvc-operator-amd64:1.12.0-RC1
openebs/cstor-csi-driver:1.12.0-RC1

openebs/jiva-csi:1.12.0-RC1
openebs/jiva-operator-amd64:1.12.0-RC1
```

**Comment by nsathyaseelan** [comment]
Observation in 1.12.0-RC1
     - Migrating cstor volumes into csi based cstor volume failed due to Version mismatch between CVC and its controller. This has been addressed through `https://github.com/openebs/upgrade/pull/16`
     - If the podAffinity is set for the application and cstor target, migration of volume was stuck. This has been addressed through `https://github.com/openebs/upgrade/pull/16`
