### ISSUE TITLE
[Release Checklist] 1.12.0

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/e2e-tests#397]
- [x] OpenShift Pipeline 
- [x] Konvoy Pipeline 
- [x] Native K8s Pipeline 
- Upgrade Pipelines
     - [x]  1.0 to 1.12.0 
     - [x]  1.1 to 1.12.0  
     - [x]  1.2 to 1.12.0  
     - [x]  1.3 to 1.12.0  
     - [x]  1.4 to 1.12.0  
     - [x]  1.5 to 1.12.0  
     - [x]  1.6 to 1.12.0  
     - [x]  1.7 to 1.12.0  
     - [x]  1.8 to 1.12.0  
     - [x]  1.9 to 1.12.0 
     - [x] 1.10.0 to 1.12.0
     - [x] 1.11.0 to 1.12.0
- ZFS Upgrade Pipelines
     - [x]  0.4 to 0.9.0 
     - [x]  0.4.1 to 0.9.0  
     - [x]  0.5 to 0.9.0  
     - [x]  0.6 to 0.9.0  
     - [x]  0.6.1 to 0.9.0
     - [x] 0.7.0 to 0.9.0 
     - [x] 0.8.0 to 0.9.0
- Manual verifications
    - [x] Verify the cstor operator and csi operator from charts 
    - [x] Helm chart validation for OpenEBS instalation
    - [x] Change SPC name while Migrate
    - [x] CSPC/CSI volume Upgrade 
- Dogfooding:
     - [x] GitLab cluster used for E2E Pipelines upgraded from 1.11.0 to 1.12.0

**Comment by kmova** [comment]
The 1.12.0 images are generated: 

```
openebs/node-disk-exporter:0.7.0
openebs/node-disk-operator:0.7.0
openebs/node-disk-manager:0.7.0
openebs/zfs-driver:0.9.0
openebs/jiva-operator-amd64:1.12.0
openebs/jiva-csi:1.12.0
openebs/migrate-amd64:1.12.0
openebs/upgrade-amd64:1.12.0
openebs/cstor-webhook-amd64:1.12.0
openebs/cstor-pool-manager-amd64:1.12.0
openebs/cstor-volume-manager-amd64:1.12.0
openebs/cspc-operator-amd64:1.12.0
openebs/cvc-operator-amd64:1.12.0
openebs/cstor-csi-driver:1.12.0
openebs/provisioner-localpv:1.12.0
openebs/velero-plugin:1.12.0
openebs/snapshot-provisioner:1.12.0
openebs/snapshot-controller:1.12.0
openebs/openebs-k8s-provisioner:1.12.0
openebs/admission-server:1.12.0
openebs/m-upgrade:1.12.0
openebs/m-exporter:1.12.0
openebs/cstor-volume-mgmt:1.12.0
openebs/cstor-pool-mgmt:1.12.0
openebs/m-apiserver:1.12.0
openebs/jiva:1.12.0
openebs/cstor-istgt:1.12.0
openebs/cstor-pool:1.12.0
openebs/linux-utils:1.12.0
```
