### ISSUE TITLE
[Release Checklist] 2.0.0

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/e2e-tests#452]
- [x] OpenShift Pipeline 
- [x] Konvoy Pipeline 
- [x] Native K8s Pipeline 
- Upgrade Pipelines
     - [x]  1.0 to 2.0.0
     - [x]  1.1 to 2.0.0
     - [x]  1.2 to 2.0.0
     - [x]  1.3 to 2.0.0  
     - [x]  1.4 to 2.0.0  
     - [x]  1.5 to 2.0.0  
     - [x]  1.6 to 2.0.0  
     - [x]  1.7 to 2.0.0 
     - [x]  1.8 to 2.0.0  
     - [x]  1.9 to 2.0.0 
     - [x] 1.10.0 to 2.0.0
     - [x] 1.11.0 to 2.0.0
     - [x] 1.12.0 to 2.0.0
- ZFS Upgrade Pipelines
     - [x]  0.4 to 0.9.1
     - [x]  0.4.1 to 0.9.1
     - [x]  0.5 to 0.9.1
     - [x]  0.6 to 0.9.1
     - [x]  0.6.1 to 0.9.1
     - [x] 0.7.0 to 0.9.1
     - [x] 0.8.0 to 0.9.1
     - [x] 0.9.0 to 0.9.1
- Dog Fooding:
    - [x] spc/cstor volume migration into cspc/cstor-csi
    -  CSPC/CSI volume Upgrade
          - [x] 1.10.0 to 2.0.0
          - [x] 1.11.0 to 2.0.0
          - [x] 1.12.0 to 2.0.0
    - [x] Migrate SPC pool into CSPC pool in gitlab production cluster
    - [x] Migrate non-csi volume into csi volume in gitlab production cluster
    - [x] Upgrade gitlab production cluster 
    - [x] Helm validation

**Comment by kmova** [comment]
2.0.0 images are generated: 

```
openebs/jiva:2.0.0
openebs/cstor-istgt:2.0.0
openebs/cstor-pool:2.0.0

openebs/linux-utils:2.0.0
openebs/node-disk-exporter:0.8.0
openebs/node-disk-operator:0.8.0
openebs/node-disk-manager:0.8.0

openebs/zfs-driver:0.9.1
openebs/provisioner-localpv:2.0.0

openebs/migrate-amd64:2.0.0
openebs/upgrade-amd64:2.0.0
openebs/cstor-webhook-amd64:2.0.0
openebs/cstor-pool-manager-amd64:2.0.0
openebs/cstor-volume-manager-amd64:2.0.0
openebs/cspc-operator-amd64:2.0.0
openebs/cvc-operator-amd64:2.0.0
openebs/cstor-csi-driver:2.0.0

openebs/openebs-k8s-provisioner:2.0.0
openebs/m-apiserver:2.0.0
openebs/snapshot-provisioner:2.0.0
openebs/snapshot-controller:2.0.0
openebs/admission-server:2.0.0
openebs/m-upgrade:2.0.0
openebs/m-exporter:2.0.0
openebs/velero-plugin:2.0.0
openebs/cstor-volume-mgmt:2.0.0
openebs/cstor-pool-mgmt:2.0.0
```

**Comment by shashank855** [comment]
SPC to CSPC migration failed in Gitlab Production cluster. As it has striped pool created with multiple disks and the pool created different rarid group for the disks.

ref: https://github.com/openebs/openebs/issues/3107
This issue has the fix in this PR :https://github.com/openebs/upgrade/pull/39
