### ISSUE TITLE
[Release Checklist] 2.4.0

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/e2e-tests#567]
- [x] OpenShift Pipeline 
- [x] Konvoy Pipeline 
- Native K8s Pipeline 
     - [x] with zfs-driver:1.2.0
     - [x] with zfs-driver:1.2.1
- Upgrade Pipelines [spc/cstor/jiva]
     - [x]  1.0 to 2.4.0 
     - [x]  1.1 to 2.4.0   
     - [x]  1.2 to 2.4.0  
     - [x]  1.3 to 2.4.0   
     - [x]  1.4 to 2.4.0   
     - [x]  1.5 to 2.4.0   
     - [x]  1.6 to 2.4.0   
     - [x]  1.7 to 2.4.0   
     - [x]  1.8 to 2.4.0   
     - [x]  1.9 to 2.4.0  
     - [x] 1.10.0 to 2.4.0 
     - [x] 1.11.0 to 2.4.0 
     - [x] 1.12.0 to 2.4.0
     - [x] 2.0.0 to 2.4.0
     - [x] 2.1.0 to 2.4.0
     - [x] 2.2.0 to 2.4.0
     - [x] 2.3.0 to 2.4.0
 - cspc/cstor csi volume upgrade
      - [x] 1.10.0 to 2.4.0
      - [x] 1.11.0 to 2.4.0
      - [x] 1.12.0 to 2.4.0
      - [x] 2.0.0 to 2.4.0
      - [x] 2.1.0 to 2.4.0
      - [x] 2.2.0 to 2.4.0
      - [x] 2.3.0 to 2.4.0
- ZFS Upgrade Pipelines
     - [x]  0.4.1 to 1.2.1
     - [x]  0.5 to 1.2.1
     - [x]  0.6.1 to 1.2.1
     - [x] 0.7.0 to 1.2.1
     - [x] 0.8.0 to 1.2.1
     - [x] 0.9.2 to 1.2.1
     - [x] 1.0.0 to 1.2.1
     - [x] 1.0.1 to 1.2.1
     - [x] 1.1.0 to 1.2.1
- Migration spc pool to cspc and cstor volume to cstor csi volume
     - [x] 1.12.0 to 2.4.0
     - [x] 2.0.0 to 2.4.0
     - [x] 2.1.0 to 2.4.0
     - [x] 2.2.0 to 2.4.0
     - [x] 2.3.0 to 2.4.0
- Manual verification
     - [x] helm validation
- Dog Fooding
     - [x] Upgrade GitLab cluster to 2.4.0

**Comment by kmova** [comment]
Images are generated: 

```
✔ openebs/linux-utils:2.4.0
✔ openebs/cstor-pool:2.4.0
✔ openebs/cstor-istgt:2.4.0
✔ openebs/jiva:2.4.0
✔ openebs/m-apiserver:2.4.0
✔ openebs/cstor-pool-mgmt:2.4.0
✔ openebs/cstor-volume-mgmt:2.4.0
✔ openebs/m-exporter:2.4.0
✔ openebs/m-upgrade:2.4.0
✔ openebs/admission-server:2.4.0
✔ openebs/openebs-k8s-provisioner:2.4.0
✔ openebs/snapshot-controller:2.4.0
✔ openebs/snapshot-provisioner:2.4.0
✔ openebs/velero-plugin:2.4.0
✔ openebs/provisioner-localpv:2.4.0
✔ openebs/cstor-csi-driver:2.4.0
✔ openebs/cvc-operator:2.4.0
✔ openebs/cspc-operator:2.4.0
✔ openebs/cstor-volume-manager:2.4.0
✔ openebs/cstor-pool-manager:2.4.0
✔ openebs/cstor-webhook:2.4.0
✔ openebs/upgrade:2.4.0
✔ openebs/migrate:2.4.0
✔ openebs/zfs-driver:1.2.0
✔ openebs/node-disk-manager:1.0.1
✔ openebs/node-disk-operator:1.0.1
✔ openebs/node-disk-exporter:1.0.1
```
