### ISSUE TITLE
[Release Checklist] 2.8.0

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/e2e-tests#623]
-  OpenShift Pipeline 
    - [x] cStor
    - [x] Jiva
    - [x] cStor-csi
- Konvoy Pipeline 
    - [x] cStor
    - [x] Jiva
    - [x] cStor-csi
- [x] zfs-localpv pipeline
- [x] lvm-localpv
- Upgrade Pipelines [spc/cstor/jiva]
     - [x]  1.7 to 2.8.0
     - [x]  1.8 to 2.8.0
     - [x]  1.9 to 2.8.0
     - [x] 1.10.0 to 2.8.0
     - [x] 1.11.0 to 2.8.0
     - [x] 1.12.0 to 2.8.0
     - [x] 2.0.0 to 2.8.0
     - [x] 2.1.0 to 2.8.0
     - [x] 2.2.0 to 2.8.0
     - [x] 2.3.0 to 2.8.0
     - [x] 2.4.0 to 2.8.0
     - [x] 2.5.0 to 2.8.0
     - [x] 2.6.0 to 2.8.0
     - [x] 2.7.0 to 2.8.0
 - cspc/cstor csi volume upgrade
      - [x] 1.10.0 to 2.8.0
      - [x] 1.11.0 to 2.8.0
      - [x] 1.12.0 to 2.8.0
      - [x] 2.0.0 to 2.8.0
      - [x] 2.1.0 to 2.8.0
      - [x] 2.2.0 to 2.8.0
      - [x] 2.3.0 to 2.8.0
      - [x] 2.4.0 to 2.8.0
      - [x] 2.5.0 to 2.8.0
      - [x] 2.6.0 to 2.8.0
      - [x] 2.7.0 to 2.8.0
- ZFS Upgrade Pipelines
     - [x] 1.0.0 to 1.6.0
     - [x] 1.0.1 to 1.6.0
     - [x] 1.1.0 to 1.6.0
     - [x] 1.2.1 to 1.6.0
     - [x] 1.3.0 to 1.6.0
     - [x] 1.4.0 to 1.6.0
     - [x] 1.5.0 to 1.6.0
- Migration spc pool to cspc and cstor volume to cstor csi volume
     - [x] 1.12.0 to 2.8.0
     - [x] 2.0.0 to 2.8.0
     - [x] 2.1.0 to 2.8.0
     - [x] 2.2.0 to 2.8.0
     - [x] 2.3.0 to 2.8.0
     - [x] 2.4.0 to 2.8.0
     - [x] 2.5.0 to 2.8.0
     - [x] 2.6.0 to 2.8.0
     - [x] 2.7.0 to 2.8.0
- Manual Validation
     - [x] Helm chart validation
- DogFooding
     - [x] GitLab prod cluster

**Comment by nsathyaseelan** [comment]
- Minimum required kubernetes version for 2.8.0 should be 1.18, For cstor operator facing the issue while deploying cstor-operator with the k8s version is 1.17
```
error: unable to recognize "https://raw.githubusercontent.com/openebs/charts/dd419fa0a6571a71bcb90042a7ba97511e4b3419/2.8.0/cstor-operator-RC1.yaml": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"
```
- While upgrade from older version to 2.8.0 getting below warning, because of earlier ndm-operator used to create these crds so these warnings are expected. Now the crds moved to the operator
```
Warning: resource customresourcedefinitions/blockdevices.openebs.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/blockdevices.openebs.io configured
Warning: resource customresourcedefinitions/blockdeviceclaims.openebs.io is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
```

- kubernetes version in pipelines
    - Konvoy - 1.17 and 1.19.6
    - Openshift - 1.18.2
    - Kubeadm - 1.20
